CREATE TABLE IF NOT EXISTS "activities" (
  "id" INTEGER NOT NULL,
  "activity" TEXT DEFAULT NULL,
  "timestamp" TIMESTAMP DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "hotels" (
  "id" INTEGER NOT NULL,
  "owner_id" INTEGER NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "property_type" VARCHAR(50) DEFAULT 'hotel',
  "description" TEXT DEFAULT NULL,
  "address" VARCHAR(255) DEFAULT NULL,
  "city" VARCHAR(100) DEFAULT NULL,
  "country" VARCHAR(100) DEFAULT NULL,
  "stars" INTEGER DEFAULT 3,
  "main_image" TEXT DEFAULT NULL,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "total_rooms" INTEGER DEFAULT 1,
  "max_guests" INTEGER DEFAULT 2,
  "price_per_night" DOUBLE PRECISION DEFAULT NULL,
  "avg_rating" DECIMAL(2,1) DEFAULT 0.0,
  "review_count" INTEGER DEFAULT 0,
  "accept_online_payments" SMALLINT DEFAULT 0,
  "stripe_account_id" VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "hotel_images" (
  "id" INTEGER NOT NULL,
  "hotel_id" INTEGER NOT NULL,
  "image_data" TEXT NOT NULL,
  "caption" VARCHAR(255) DEFAULT NULL,
  "is_primary" SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "hotel_reviews" (
  "id" INTEGER NOT NULL,
  "hotel_id" INTEGER NOT NULL,
  "user_id" INTEGER DEFAULT NULL,
  "rating" DECIMAL(2,1) NOT NULL,
  "review_text" TEXT DEFAULT NULL,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "promotions" (
  "id" INTEGER NOT NULL,
  "title" VARCHAR(255) NOT NULL,
  "description" TEXT DEFAULT NULL,
  "discount_percent" INTEGER DEFAULT 0,
  "valid_until" DATE DEFAULT NULL,
  "image_data" TEXT DEFAULT NULL,
  "is_active" SMALLINT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "property_reservations" (
  "id" INTEGER NOT NULL,
  "property_id" INTEGER NOT NULL,
  "guest" VARCHAR(255) NOT NULL,
  "user_id" INTEGER DEFAULT NULL,
  "start_date" DATE NOT NULL,
  "nights" INTEGER NOT NULL,
  "total_price" DOUBLE PRECISION NOT NULL,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "payment_status" VARCHAR(20) DEFAULT 'pending',
  "payment_id" VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "reservations" (
  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "room_id" INTEGER NOT NULL,
  "guest" VARCHAR(255) NOT NULL,
  "user_id" INTEGER DEFAULT NULL,
  "start_date" DATE NOT NULL,
  "nights" INTEGER NOT NULL,
  "payment_status" VARCHAR(20) DEFAULT 'pending',
  "payment_id" VARCHAR(255) DEFAULT NULL,
  "total_price" DOUBLE PRECISION DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "rooms" (
  "id" INTEGER NOT NULL,
  "hotel_id" INTEGER DEFAULT NULL,
  "number" INTEGER NOT NULL,
  "price" DOUBLE PRECISION NOT NULL,
  "type" VARCHAR(50) NOT NULL,
  "beds" INTEGER DEFAULT NULL,
  "jacuzzi" SMALLINT DEFAULT NULL,
  "image_data" TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "trending_destinations" (
  "id" INTEGER NOT NULL,
  "name" VARCHAR(100) NOT NULL,
  "country" VARCHAR(100) DEFAULT 'Bulgaria',
  "image_data" TEXT DEFAULT NULL,
  "property_count" INTEGER DEFAULT 0,
  "display_order" INTEGER DEFAULT 0,
  "is_active" SMALLINT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER NOT NULL,
  "username" VARCHAR(255) DEFAULT NULL,
  "password_hash" TEXT DEFAULT NULL,
  "is_admin" SMALLINT DEFAULT 0,
  "role" VARCHAR(20) DEFAULT 'user',
  "profile_image" TEXT DEFAULT NULL,
  "email" VARCHAR(255) DEFAULT NULL,
  "phone" VARCHAR(20) DEFAULT NULL,
  "address" VARCHAR(500) DEFAULT NULL,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "google_id" VARCHAR(255) DEFAULT NULL,
  "account_type_request" VARCHAR(20) DEFAULT 'user'
);

ALTER TABLE "activities" ADD PRIMARY KEY ("id");
CREATE INDEX IF NOT EXISTS idx_activities_timestamp ON "activities" ("timestamp");

ALTER TABLE "hotels" ADD PRIMARY KEY ("id");
CREATE INDEX IF NOT EXISTS idx_hotels_owner ON "hotels" ("owner_id");

ALTER TABLE "hotel_images" ADD PRIMARY KEY ("id");
CREATE INDEX IF NOT EXISTS idx_hotel_images_hotel ON "hotel_images" ("hotel_id");

ALTER TABLE "hotel_reviews" ADD PRIMARY KEY ("id");
CREATE INDEX IF NOT EXISTS idx_hotel_reviews_hotel ON "hotel_reviews" ("hotel_id");
CREATE INDEX IF NOT EXISTS idx_hotel_reviews_user ON "hotel_reviews" ("user_id");

ALTER TABLE "promotions" ADD PRIMARY KEY ("id");

ALTER TABLE "property_reservations" ADD PRIMARY KEY ("id");
CREATE INDEX IF NOT EXISTS idx_property_reservations_property ON "property_reservations" ("property_id");
CREATE INDEX IF NOT EXISTS idx_property_reservations_user ON "property_reservations" ("user_id");

ALTER TABLE "rooms" ADD PRIMARY KEY ("id");
CREATE UNIQUE INDEX IF NOT EXISTS idx_rooms_number ON "rooms" ("number");
CREATE INDEX IF NOT EXISTS idx_rooms_hotel ON "rooms" ("hotel_id");

ALTER TABLE "trending_destinations" ADD PRIMARY KEY ("id");

ALTER TABLE "users" ADD PRIMARY KEY ("id");
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username ON "users" ("username");
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_google_id ON "users" ("google_id");

--
-- Constraints for dumped tables
--

--
-- Foreign keys
--
ALTER TABLE "hotels" ADD CONSTRAINT "fk_hotels_owner" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "hotel_images" ADD CONSTRAINT "fk_hotel_images_hotel" FOREIGN KEY ("hotel_id") REFERENCES "hotels" ("id") ON DELETE CASCADE;
ALTER TABLE "hotel_reviews" ADD CONSTRAINT "fk_hotel_reviews_hotel" FOREIGN KEY ("hotel_id") REFERENCES "hotels" ("id") ON DELETE CASCADE;
ALTER TABLE "hotel_reviews" ADD CONSTRAINT "fk_hotel_reviews_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "property_reservations" ADD CONSTRAINT "fk_property_reservations_property" FOREIGN KEY ("property_id") REFERENCES "hotels" ("id") ON DELETE CASCADE;
ALTER TABLE "property_reservations" ADD CONSTRAINT "fk_property_reservations_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "reservations" ADD CONSTRAINT "fk_reservations_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "rooms" ADD CONSTRAINT "fk_rooms_hotel" FOREIGN KEY ("hotel_id") REFERENCES "hotels" ("id") ON DELETE CASCADE;
COMMIT;
