"""
Converts MySQL dump (register_user (5).sql) to PostgreSQL-compatible SQL for Supabase.
Handles binary-to-base64 conversion for image columns.
Usage: python convert_to_pgsql.py
"""
import re
import base64
import binascii

INPUT_FILE = r"C:\Users\Students\Downloads\stayora-main\stayora-main\register_user (5).sql"
OUTPUT_FILE = "supabase_import.sql"


def mysql_type_to_pg(col_type):
    col_type = col_type.strip().lower()
    if col_type.startswith('int('):
        return 'INTEGER'
    if col_type.startswith('tinyint('):
        return 'SMALLINT'
    if col_type in ('longblob', 'mediumblob', 'blob'):
        return 'TEXT'
    if col_type == 'datetime':
        return 'TIMESTAMP'
    if col_type == 'float':
        return 'DOUBLE PRECISION'
    if col_type == 'double':
        return 'DOUBLE PRECISION'
    if col_type.startswith('decimal(') or col_type.startswith('numeric('):
        return col_type.upper()
    if col_type.startswith('varchar('):
        return col_type.upper()
    if col_type == 'text':
        return 'TEXT'
    if col_type == 'date':
        return 'DATE'
    return col_type.upper()


def convert_sql(mysql_sql):
    lines = mysql_sql.split('\n')
    out_lines = []
    in_create = False
    in_insert = False
    table_name = None
    columns = []

    for line in lines:
        stripped = line.strip()

        # Skip MySQL-specific headers/footers
        if any(stripped.startswith(x) for x in [
            'SET SQL_MODE', 'START TRANSACTION', 'SET time_zone',
            '/*!40101', '-- phpMyAdmin', '-- version', '-- Host',
            '-- Generation Time', '-- Server version', '-- PHP Version',
            '-- Database:', '-- --------------------------------------------------------',
            '/*!40101 SET', 'SET NAMES', '-- Table structure',
            '-- Dumping data', '-- Indexes for', '-- AUTO_INCREMENT for',
            '-- Constraints for', 'ALTER TABLE `reservations` ADD KEY',
            'ALTER TABLE `reservations_backup`',
        ]):
            if stripped.startswith('-- ') and not stripped.startswith('-- Table'):
                out_lines.append(line)
            continue

        # Skip backup table
        if 'reservations_backup' in stripped:
            continue
        if stripped.startswith('INSERT INTO `reservations_backup`'):
            in_insert = False
            continue
        if in_insert and 'reservations_backup' in ''.join(out_lines[-3:]):
            if stripped == '' or stripped.startswith('INSERT') or stripped.startswith('--'):
                in_insert = False
            continue

        # CREATE TABLE conversion
        if stripped.startswith('CREATE TABLE'):
            in_create = True
            table_name = re.search(r'`(\w+)`', stripped).group(1)
            out_lines.append(f'CREATE TABLE IF NOT EXISTS "{table_name}" (')
            continue

        if in_create:
            if stripped.startswith(')'):
                in_create = False
                out_lines.append(');')
                continue
            col_match = re.match(r'\s+`(\w+)`\s+(.+?)(,|$)', line)
            if col_match:
                col_name = col_match.group(1)
                col_rest = col_match.group(2)
                # Remove engine/charset lines
                if col_rest.strip().startswith('ENGINE='):
                    continue
                # Convert type
                col_parts = col_rest.split()
                pg_type = mysql_type_to_pg(col_parts[0])
                rest = ' '.join(col_parts[1:])
                rest = rest.replace('NOT NULL', 'NOT NULL')
                rest = rest.replace('DEFAULT current_timestamp()', 'DEFAULT CURRENT_TIMESTAMP')
                rest = rest.replace("DEFAULT 'current_timestamp()'", "DEFAULT CURRENT_TIMESTAMP")
                rest = rest.replace("DEFAULT 'current_timestamp()", "DEFAULT CURRENT_TIMESTAMP")
                rest = rest.replace("DEFAULT '0.0'", "DEFAULT 0.0")
                rest = rest.replace('DEFAULT 0.0', 'DEFAULT 0.0')
                rest = rest.replace('DEFAULT NULL', 'DEFAULT NULL')
                rest = rest.replace('AUTO_INCREMENT', 'GENERATED BY DEFAULT AS IDENTITY')
                # Clean up trailing comma in rest
                if col_match.group(3) == ',':
                    out_lines.append(f'  "{col_name}" {pg_type} {rest.strip()},')
                else:
                    out_lines.append(f'  "{col_name}" {pg_type} {rest.strip()}')
                continue
            # Handle constraint lines in CREATE
            if stripped.startswith('  PRIMARY KEY'):
                out_lines.append(stripped.replace('`', '"'))
                continue
            if stripped.startswith('  UNIQUE KEY'):
                out_lines.append(stripped.replace('`', '"').replace('UNIQUE KEY', 'UNIQUE'))
                continue
            if stripped.startswith('  KEY'):
                out_lines.append(stripped.replace('`', '"').replace('KEY', 'INDEX'))
                continue
            if stripped.startswith('  CONSTRAINT') or stripped.startswith('  INDEX'):
                out_lines.append(stripped.replace('`', '"'))
                continue
            out_lines.append(line)
            continue

        # INSERT INTO conversion
        if stripped.startswith('INSERT INTO'):
            in_insert = True
            # Convert binary hex values to base64
            def hex_to_base64(match):
                hex_str = match.group(1)
                try:
                    raw_bytes = binascii.unhexlify(hex_str)
                    b64 = base64.b64encode(raw_bytes).decode('ascii')
                    return f"'{b64}'"
                except Exception:
                    return f"'__BINARY_DATA__'"

            converted = re.sub(r"0x([0-9a-fA-F]+)", hex_to_base64, stripped)
            # Also handle hex values without 0x prefix but in hex context
            converted = converted.replace('`', '"')
            out_lines.append(converted)
            continue

        if in_insert:
            if stripped == '':
                in_insert = False
            else:
                def hex_to_base64(match):
                    hex_str = match.group(1)
                    try:
                        raw_bytes = binascii.unhexlify(hex_str)
                        b64 = base64.b64encode(raw_bytes).decode('ascii')
                        return f"'{b64}'"
                    except Exception:
                        return f"'__BINARY_DATA__'"

                converted = re.sub(r"0x([0-9a-fA-F]+)", hex_to_base64, stripped)
                converted = converted.replace('`', '"')
                out_lines.append(converted)
            continue

        # ALTER TABLE for indexes/constraints
        if stripped.startswith('ALTER TABLE'):
            # Convert ADD PRIMARY KEY, ADD UNIQUE, ADD CONSTRAINT, ADD INDEX
            conv = stripped.replace('`', '"')
            # Handle MODIFY (AUTO_INCREMENT reset) - skip, handled by IDENTITY
            if 'MODIFY' in conv:
                continue
            # Add KEY becomes ADD INDEX
            conv = re.sub(r'ADD KEY', 'ADD INDEX', conv)
            # Add PRIMARY KEY
            out_lines.append(conv)
            continue

        out_lines.append(line)

    return '\n'.join(out_lines)


if __name__ == '__main__':
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        mysql_sql = f.read()

    pg_sql = convert_sql(mysql_sql)

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(pg_sql)

    print(f"Converted SQL written to {OUTPUT_FILE}")
    print(f"Open {OUTPUT_FILE}, copy its contents, and paste into Supabase SQL Editor.")
